# Generated by Django 2.0.1 on 2018-01-19 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_auto_20180118_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_pub',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_scraped',
        ),
    ]
